@startuml
'https://plantuml.com/component-diagram


component app
component evolution
component road
component simulation
component common
component box2d <<external>>
component SFML <<external>>
component ImGUI <<external>>

skinparam component {
    backgroundColor<<external>> DarkGray
}

app ..> evolution: use
app ..> simulation: use
app ..> road: use
app ..> SFML: use
app ..> ImGUI: use

evolution ..> common: use

simulation ..> common: use
simulation ..> box2d: use
simulation ..> road: use



@enduml