@startuml
'https://plantuml.com/class-diagram

package simulation {
    class Simulation {
        -cars: vector<Car>
        -road: Road
        +Simulation(vector<Car> cars, Road road)
        +void step()
        +bool isFinished() const
    }

    class Car {
        -ID id
        +float distance() const
        +float time() const
        +bool isAlive() const
    }

    class Road {
        -ID id
    }

}
@enduml