# This starter workflow is for a CMake project running on multiple platforms. There is a different starter workflow if you just want a single platform.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-single-platform.yml
name: CMake on multiple platforms

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: install dependencies
      run: |
          apt-get update
          apt-get install sfml

    - name: build
      shell: bash
      run: |
            cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug
            cmake --build build

    - name: Run tests
      run: >
        ctest --test-dir build
